# Generated by Django 3.1.1 on 2020-11-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mark',
            name='name',
        ),
        migrations.AddField(
            model_name='mark',
            name='song_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.song'),
            preserve_default=False,
        ),
    ]
