# Generated by Django 3.1.1 on 2020-12-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_mark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='requests',
        ),
    ]
