# Generated by Django 3.1.4 on 2020-12-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_song_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
